language: python
python: 3.6
install: pip install -r requirements.txt
script: python manager.py test

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: cd-messenger-001
  run: python manager.py migrate
  on: master