"""empty message

Revision ID: 4cf000ae7a6b
Revises: f6c31092db98
Create Date: 2020-07-25 10:55:46.896337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cf000ae7a6b'
down_revision = 'f6c31092db98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('channel_creation', sa.DateTime(), nullable=True))
    op.add_column('channels', sa.Column('channel_creator', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'channels', 'users', ['channel_creator'], ['id'])
    op.add_column('users', sa.Column('channel', sa.Integer(), nullable=True))
    op.drop_constraint('users_own_channel_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'channels', ['channel'], ['id'])
    op.drop_column('users', 'own_channel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('own_channel', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_own_channel_fkey', 'users', 'channels', ['own_channel'], ['id'])
    op.drop_column('users', 'channel')
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.drop_column('channels', 'channel_creator')
    op.drop_column('channels', 'channel_creation')
    # ### end Alembic commands ###
