"""empty message

Revision ID: 78aa93b5d336
Revises: 54ae8a0c15bc
Create Date: 2020-07-07 10:08:01.356841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78aa93b5d336'
down_revision = '54ae8a0c15bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('joined_channel', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('own_channel', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'channels', ['joined_channel'], ['id'])
    op.create_foreign_key(None, 'users', 'channels', ['own_channel'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'own_channel')
    op.drop_column('users', 'joined_channel')
    # ### end Alembic commands ###
