"""empty message

Revision ID: f6c31092db98
Revises: 78aa93b5d336
Create Date: 2020-07-07 11:19:47.141006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6c31092db98'
down_revision = '78aa93b5d336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_joined_channel_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'joined_channel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('joined_channel', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_joined_channel_fkey', 'users', 'channels', ['joined_channel'], ['id'])
    # ### end Alembic commands ###
